# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f3061e95c46df173ee38b2ed583ffc692f48d38bd44093aa7caa778de98e9004fc3b01929b64b977dd349c4f52df0d001768ae2eac55de9b3e8779d6c47e5c

test:
  secret_key_base: 76e04c7a3c6ed655b56380bd730c4470957ccadcf5a54173c813ca0d680a1cfb06d6a0164cb3b8d36caa6cf09848a37671cefd16f018390196f4227bb0795887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
